### ISSUE TITLE
Failed to recover items from input

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Backup-Extension#10]
Hey
I have imported .xml file. But now when i open the page editor.

Page builder was empty, and in console there was an error :

Failed to recover items from input SyntaxError: Unexpected token c

http://prntscr.com/7ivy25

See how page builder looks :

http://prntscr.com/7ivyf8

Can you please look into this ? I am really worried. I have completed theme now i was making one click demo import and saw this error.

Thanks!

> https://wordpress.org/support/topic/failed-to-recover-items-from-input?replies=1#post-7089972

**Comment by valeriuzdrobau** [comment]
Send me please access details to the valeriuzdrobau@gmail.com email address, to examine the issue.

**Comment by coolsdudes1992** [comment]
just sent you an email. Please take a look. Thank you so much !

**Comment by coolsdudes1992** [comment]
Okay i got the error why it is occurring. I have written an html in special heading some thing like <span class="maincolor">Theme</span> 

Now these double quotations causes this issue. If i replace it with single quotes it works. JSON isn't pasrsing if i put double quotes. I think it should encode or some thing like that before storing ?

**Comment by valeriuzdrobau** [comment]
The problem was repaired in version 1.3.5 of [Unyson-PageBuilder-Extension](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension).
