### ISSUE TITLE
On Demand Backups fail most of the time

### ISSUE THREAD

**Issue by rawcreative** [ThemeFuse/Unyson-Backup-Extension#11]
When trying to run a manual full backup on an install containing a large amount of files/uploads, the backup will typically get to around 50% before PHP's max execution limit is hit. Since there are no checks in place for situations like this, the backup hangs indefinitely and even trying to cancel the backup hangs in a 'Cancelling' state. Granted changing PHP's max execution limit could potentially solve this issue in some cases, but not everyone has access to change that. There needs to be some checks in place to handle these situations.

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
