### ISSUE TITLE
Unable to successfully install demo content

### ISSUE THREAD

**Issue by NazarkinRoman** [ThemeFuse/Unyson-Backup-Extension#14]
Hi!

Recently encountered that stranger bug when trying to import demo data:

```
Fatal error: Call to a member function query() on boolean in /path_to_wp/wp-content/plugins/unyson/framework/extensions/backup/includes/lib/srdb.class.php on line 578
```

Demo data is inserted.. But without any processing(such as replace URLs and change table prefixes)..
PDO extension is installed & activated on the system, used latest versions of Unyson(2.4.1) and Backup extension(1.0.8). Seems that `$this->db` variable is not set.

**Comment by valeriuzdrobau** [comment]
Can you give me access to your server?

**Comment by NazarkinRoman** [comment]
@valeriuzdrobau both installations was on my localhost(same computer).. 

**My workflow:**
1. Install latest WordPress version, update all uplugins
2. Install my theme(package created via _Create demo install_ option in backup extension, also latest version)
3. Install `Unyson` plugin, `Contact form 7` plugin and `Bootstrap for Contact form 7` plugin
4. Install all required extensions(seo, analytics, backup, page builder, sliders)
5. Go to _Tools > Install demo content_
6. Click on button, confirm action and wait for awhile and... See this error.

**Some additional information:**
- site addresses is `http://wp-dev/` and `http://wp-test/`, without a root-domains.
- phpinfo output - http://pastebin.com/raw.php?i=5VvJ7hHP
- also, I have this errors in PHP log after import:

```
[22-Jul-2015 15:32:26 UTC] 1049: Unknown database 'wordpress_test'
[22-Jul-2015 15:33:37 UTC] WordPress database error Can't DROP 'slug'; check that column/key exists for query ALTER TABLE wp_terms DROP INDEX slug, ADD INDEX slug(slug(191)) made by wp_upgrade, pre_schema_upgrade
```

**Comment by valeriuzdrobau** [comment]
What version of MySQL you use?

**Comment by NazarkinRoman** [comment]
![2015-07-23 14-18-43 window](https://cloud.githubusercontent.com/assets/1572715/8846030/6008905c-313d-11e5-9462-ddc0ce846f28.png)
MySQL - 5.5.38
