### ISSUE TITLE
Create Demo Content - No sql file & File Permission on Demo Content Import

### ISSUE THREAD

**Issue by ankitaraikundalia** [ThemeFuse/Unyson-Backup-Extension#16]
Hi,

Using the Backup extension, I created a demo content.

Referring [this](http://manual.unyson.io/en/latest/extension/contentdemoinstall/index.html#content) link, it tells that there will be a file named `database.sql` in auto-install folder.

However, the zip folder which gets downloaded has a file named `database.txt`, not `database.sql`

Further, when I install this theme on another site, and try to import the demo content, I get the error `File System: Not Enough Permissions`. Below is the screenshot of error:

![demo-content-import](https://cloud.githubusercontent.com/assets/9928664/9062114/f4125a90-3add-11e5-848b-78fa4ab3d469.png)

The file permissions to the `wp-content/upload` folder is set to 777.

**Comment by valeriuzdrobau** [comment]
Hi,
   From the beginning it was called database.sql, now is database.txt. Due to [this code](https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/a725e30624c33aef19f76a6e3cb86ccf69cd89fb/includes/processes/class-fw-backup-process-auto-install.php#L44-L51), the import will work in both cases.

 Tell me please, which is the result of this code: 

```
$method = defined('FS_METHOD') ? FS_METHOD : false;
var_dump($method);
```

**Comment by ankitaraikundalia** [comment]
@valeriuzdrobau FS_METHOD is set to direct.

On removing the code `define('FS_METHOD', 'direct');` from wp-config.php file, FTP credentials are asked on clicking the 'Import Content Demo' button

**Comment by valeriuzdrobau** [comment]
Try to replace[ this line](https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/master/includes/helpers/class-fw-backup-helper-file-system.php#L323) with the following code: 

```
$d = $wp_filesystem->wp_content_dir() . uniqid('check_permissions_');
```

**Comment by valeriuzdrobau** [comment]
You tried to change what I wrote in the previous message? Tell me please the result.

**Comment by valeriuzdrobau** [comment]
Due to inactivity I close this issue. Feel free to reopen it at any time.

**Comment by ankitaraikundalia** [comment]
@valeriuzdrobau , Sorry for late reply.

I replaced the code and it worked fine.

So, will you be making this change in the next update?

**Comment by valeriuzdrobau** [comment]
I [solved](https://github.com/ThemeFuse/Unyson-Backup-Extension/commit/46a9a8529a9940e31130cee46358fa2524a468e3), you can test [1.0.11 version](https://github.com/ThemeFuse/Unyson-Backup-Extension/releases/tag/v1.0.11).
