### ISSUE TITLE
failure to install demo content

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Backup-Extension#17]
> https://wordpress.org/support/topic/failure-to-install-demo-content

When installing 'demo content' appeared following error in the bank what to do to correct it?

WordPress database error: [Table 'proadsp.wp_categories' doesn't exist]
SELECT \* FROM wp_categories ORDER BY cat_ID

WordPress database error: [Table 'proadsp.wp_post2cat' doesn't exist]
SELECT post_id, category_id FROM wp_post2cat GROUP BY post_id, category_id

WordPress database error: [Table 'proadsp.wp_linkcategories' doesn't exist]
SELECT cat_id, cat_name FROM wp_linkcategories

WordPress database error: [Unknown column 'link_category' in 'field list']
SELECT link_id, link_category FROM wp_links

**Comment by valeriuzdrobau** [comment]
Send me please access details to the valeriuzdrobau@gmail.com email address, to examine the issue.

**Comment by valeriuzdrobau** [comment]
You tell me what versions of PHP and MySQL you have?

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
