### ISSUE TITLE
Infinite number of backups created

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Backup-Extension#18]
I tested, and is created a infinite number of backups, and after canceled the process, 12 new backups created, but the Backup Archive have 0 backups:
http://www.awesomescreenshot.com/image/558240/21a0bafe76fbf7431fbd753b99143ff3

On the disc I have this 12 backups.

**Comment by andronic90** [comment]
This bug appear only with the 1.0 version of content install this: (that contain user_meta table)

https://dl.dropboxusercontent.com/u/106935872/autointall%20la%20teme%20themefuse/exposure-install.zip

With the latest version of demo-content work well.
I don't know what is the problem, you can download this version of content install : https://dl.dropboxusercontent.com/u/106935872/autointall%20la%20teme%20themefuse/exposure-install.zip and test it (I think that many users have and this content install, the new users don't have this problem)

How to simulate:
1. make content install from dropbox link
2. add a page or a post (i make this for know after backup restore that project are restored to previous version)
3. go to backup, and make a full backup
After this action backup create infinite number of backups zip (until I stopped the local server)

Attention : if you can't simulate use the username to wordpress project (username: admin password: 1)

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
