### ISSUE TITLE
Problem on content install

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Backup-Extension#19]
Error on content install on test server:
http://www.awesomescreenshot.com/image/595056/776079febf3ffaa9b642038e8a8fc99f

If you need more information I can send the details in private

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
