### ISSUE TITLE
Cancelling process of backups

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Unyson-Backup-Extension#20]
Cancelling backups is not possible to delete: http://content.screencast.com/users/andronic90/folders/Jing/media/7c898c7a-85e5-4b19-900c-443e828dce10/2015-09-22_1825.png

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
