### ISSUE TITLE
Demo content installation problem (home URL)

### ISSUE THREAD

**Issue by praveenrchauhan** [ThemeFuse/Unyson-Backup-Extension#22]
I am creating a demo install from a site whose path is something like https://example.com/subdir1/subdir2/wordpressdir (referred as First site in further communication)

I am installing the above demo content on another site whose path is something like http://example1.com (referred as Second site in further communication)

After installing the demo content, the menu links are re-directing to the First site, instead of the Second site. On further inspecting the issue, I found that the Site Address (URL) in the backend is being replaced with the URL of the First site. Ideally, this option should not be replaced.

Can you please look into this issue and provide a fix for the same?

**Comment by ghost** [comment]
We are working on Backup v2 and there will be fixed this issue.

At the moment I don't know (and don't have time) how to fix this problem in current extension.

You can try to inspect and fix it yourself.

**Comment by praveenrchauhan** [comment]
Thanks for the response.
Can you please tell me by when the Backup extension v2 will be released?

**Comment by ghost** [comment]
We don't know because it reached the Alpha version and now we are facing some [problems on testing](https://github.com/ThemeFuse/Unyson/issues/882#issuecomment-148345195)

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
