### ISSUE TITLE
500 internal server error on demo content install

### ISSUE THREAD

**Issue by praveenrchauhan** [ThemeFuse/Unyson-Backup-Extension#23]
I got 500 internal server error while installing the demo content on my site. Since it was taking a long time to install, I suspected that there might be some issue with the script execution. 

When I enabled the debug mode, I got the max execution timeout fatal error. I am attaching the screenshot which could help you to debug from where the problem is happening.

![500_error_content_install](https://cloud.githubusercontent.com/assets/6702040/10515580/bb47780e-7371-11e5-8f38-6565eeb546d3.png)

**Comment by ghost** [comment]
Sorry, [same response](https://github.com/ThemeFuse/Unyson-Backup-Extension/issues/22#issuecomment-148375958)

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
