### ISSUE TITLE
Multiple demo install - one main folder

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson-Backup-Extension#24]
Hello, 

At this moment I am trying to integrate this option to the theme: https://github.com/ThemeFuse/Unyson-Backup-Extension/issues/4

The issue is that there will be multiple auto-installation folders in the theme root folder. But if I will put all auto-install files in one main folder, then the "content install" option will disappear from admin menu. Is there anything what I can do about it?

Also - will you update the _FW_Extension_Backup::get_auto_install_dir()_ function to support multiple demo content?
And is there any way how I can update this class function from my theme?

**Comment by ghost** [comment]
Hello,

We are working on Backup v2, it's done 60%

Sorry, I don't know how to make current extension (v1) to work with multiple demo installs (and don't have time to investigate it).

**Comment by pear1** [comment]
Can I test Backup v2 extension?

**Comment by ghost** [comment]
It's not ready for testing yet

Follow this repository issues https://github.com/ThemeFuse/Unyson-Extensions-Approval

There we put all extensions before they are publicly released

**Comment by pear1** [comment]
Thank you.

When roughly do you plan to release it?

**Comment by ghost** [comment]
In a few days.

**Comment by pear1** [comment]
Great, can't wait.

**Comment by ghost** [comment]
We too

**Comment by pear1** [comment]
Hello,

Are there any news about Backup v2 extension?

**Comment by ghost** [comment]
Still in progress
