### ISSUE TITLE
Invalid source dir error.

### ISSUE THREAD

**Issue by sonnnaht** [ThemeFuse/Unyson-Backup-Extension#25]
I follow your guide http://manual.unyson.io/en/latest/extension/backups/.

But I got a error.
Please check it. 
Thanks.

![untitled_22](https://cloud.githubusercontent.com/assets/14999196/15786287/07105eba-29e6-11e6-900a-647b63fe9d93.png)

**Comment by ghost** [comment]
Show your code please.

**Comment by sonnnaht** [comment]
`<?php if (!defined('FW')) die('Forbidden');
/**
 * @var string $uri Demo directory url
 */

$manifest = array();
$manifest['title'] = __('Awesome Demo', 'domain');
$manifest['screenshot'] = $uri . '/screenshot.png';
$manifest['preview_link'] = 'https://your-site.com/demo/awesome';`

Please check it.

**Comment by sonnnaht** [comment]
```
<?php if (!defined('FW')) die('Forbidden');
/**
 * @var string $uri Demo directory url
 */

$manifest = array();
$manifest['title'] = __('Awesome Demo', 'domain');
$manifest['screenshot'] = 'screenshot.png';
$manifest['preview_link'] = 'https://your-site.com/demo/awesome';
```

Pleas check it.

**Comment by sonnnaht** [comment]
```
<?php if (!defined('FW')) die('Forbidden');
/**
 * @var string $uri Demo directory url
 */

$manifest = array();
$manifest['title'] = __('Awesome Demo', 'domain');
$manifest['screenshot'] = 'screenshot.png';
$manifest['preview_link'] = 'https://your-site.com/demo/awesome';
```

Please check it.

**Comment by sonnnaht** [comment]
Oh sorry.
I just imported successfull.
But I get message "Operation timed out after 5007 milliseconds with 0 bytes received".
Can please you clear it?
Thanks a lot!

**Comment by ghost** [comment]
You get that error every time, or some times?

**Comment by sonnnaht** [comment]
Yes. it some times.

**Comment by ghost** [comment]
So your demo is on localhost in `{theme}/demo-content/{demo-name}` but you get error that it can't be downloaded?

**Comment by sonnnaht** [comment]
I'm not sure it is message downloaded, but my demo in localhost `{theme}/demo-content/{demo-name}`

**Comment by ghost** [comment]
Can you give me teamviewer access?

**Comment by saiful-droit** [comment]
I am Faced This type of Problem, But I can't solve this issues. Please help me, any one. My file structure and code showing this screenshot below. 
![screenshot_2](https://cloud.githubusercontent.com/assets/20698608/17205751/1a86a036-54ce-11e6-823d-53fed874ea92.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/20698608/17205752/1a8fa762-54ce-11e6-9ff2-ca8ccc3e2bfb.png)

**Comment by ghost** [comment]
@saiful-droit http://manual.unyson.io/en/latest/extension/backups/index.html#demos-bundled-in-theme

Step 2: **Extract** the zip in `{theme}/demo-content/{demo-name}/`

**Comment by saiful-droit** [comment]
Again I tested that, {theme}/demo-content/{demo-name}/theme-unit-test-data.xml. But Again show this type of message. I read this documentation properly but I don't know what i missed. Please send me any tutorial which is help for me. Thank you for replay.

**Comment by ghost** [comment]
What is `theme-unit-test-data.xml`?

[This is the tutorial](http://manual.unyson.io/en/latest/extension/backups/index.html#demos-bundled-in-theme), please read carefully.

**Comment by saiful-droit** [comment]
Thank you very much. I understand for this issues and solve this issues..

**Comment by dynacorp** [comment]
i am having the same issue...please would you mind checking it out for me @moldcraft....
![screenshot 136](https://cloud.githubusercontent.com/assets/20915993/17500675/7fec748c-5dcf-11e6-9aa3-efc352e1e197.png) help me please,..client is really on my neck
![screenshot 137](https://cloud.githubusercontent.com/assets/20915993/17500838/4328d23c-5dd1-11e6-8770-b4bd8d5680aa.png)

**Comment by saiful-droit** [comment]
1. Create Content Backup

**Comment by saiful-droit** [comment]
1. Create Content Backup 
   ![screenshot_1](https://cloud.githubusercontent.com/assets/20698608/17542348/a1a5565a-5ee9-11e6-821e-99eecb2aab4e.png)
2. Extract the zip in {theme}/demo-content/{demo-name}/
   ![screenshot_2](https://cloud.githubusercontent.com/assets/20698608/17542360/b69fea66-5ee9-11e6-82fb-8aa5ebaab74a.png)
   I hope it's help for u..

**Comment by dynacorp** [comment]
thanks for the response droit it no longer says invalid dir but now it just goes straight to the homepage with no demo installed

**Comment by dynacorp** [comment]
thanks for the response droit it no longer says invalid dir but now it just
goes straight to the homepage with no demo installed

**Comment by saiful-droit** [comment]
Please give me your site url..

**Comment by dynacorp** [comment]
thriveshuttle.org/new

**Comment by dynacorp** [comment]
give me your mail so ill give you the login details

**Comment by saiful-droit** [comment]
ok, please note down.  **saiful.droitlab@gmail.com**

**Comment by vanok85** [comment]
Hi ! I can't extract the zip file.
I get error 
![image](https://cloud.githubusercontent.com/assets/9929481/23213859/aca7eef4-f91d-11e6-920d-610ede7d79e4.png)

**Comment by vanok85** [comment]
Hi ! I can't extract the zip file.
I get error 
![image](https://cloud.githubusercontent.com/assets/9929481/23213900/cf7b5f6a-f91d-11e6-9ccc-fa5030368bf9.png)

**Comment by ghost** [comment]
@vanok85 I don't know why it happens. I need your admin and ftp credentials to inspect the problem. If you can, send them to `moldcraft[at]email.com`

**Comment by alymohamedhassan** [comment]
My problem is that it says: "Execution time exceeded 10 seconds"

**Comment by ghost** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/releases/tag/v2.0.23
