### ISSUE TITLE
Hanging at Directory Cleanup

### ISSUE THREAD

**Issue by RtypeStudios** [ThemeFuse/Unyson-Backup-Extension#26]
I've installed unyson via theme fuse on my blog. The application is getting stuck at the directory clean up:

When I try and install the demo content:

![image](https://cloud.githubusercontent.com/assets/990114/25512895/ab2660ba-2c03-11e7-8bbd-ab57daf92507.png)

or when taking a backup we get the same issue:

![image](https://cloud.githubusercontent.com/assets/990114/25512934/f12b9170-2c03-11e7-9f26-60c651e58e3a.png)

I've left it for hours doesn't seem to recover, just sites there polling without ever finishing.

No errors are appearing in:
wordpress debug
nginx logs
php-fqm logs

I'm running Ubuntu 16.04 with PHP 7.0 running behind nginx 1.10.0.

**Comment by RtypeStudios** [comment]
closing posting in the wrong place

**Comment by GheorgheP** [comment]
It is in the right place.
Are you running it on a local machine?
