### ISSUE TITLE
Multiple demo install

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Backup-Extension#4]
> @maiakhoa
> Do we have any way to support multiple demo install ?
> now, we can install one demo in folder auto-install

**Comment by ghost** [comment]
I think this is relevant for generic themes that can be used in different ways (has multiple demos) : one page, slider frontpage, full width, small width, etc. [for e.g.](http://www.kriesi.at/themedemo/?theme=enfold-overview)

**Comment by maiakhoa** [comment]
yes, it is. Could you guide me how to archive that functions ?

**Comment by sergiubagrin** [comment]
@maiakhoa - Right now we don't have this option. I will investigate this option.

**Comment by xperter** [comment]
I am also looking  something Like this. 
But it will be ok if we add a select option with demo name. and then select the demo name which i like to install.  and when i press <strong>Import demo content</strong>
The will catch the demo Which i have select  then install the demo content. is it possible ?? 

I really badly need like this. we are creating one page theme. so it will be great if i can select the demo which i like to install.

Thanks for your help

**Comment by danyj** [comment]
:+1:

**Comment by Ataurr** [comment]
@sergiubagrin @moldcraft   brothers.  any possibility to include this ?  can you give us direction so we can build by our self. 

Thanks much

**Comment by ghost** [comment]
I haven't worked on the Backup extension and I am not familiar with the code. @vbarbarosh can tell if this is possible or not.

**Comment by vbarbarosh** [comment]
> @maiakhoa
> Do we have any way to support multiple demo install ?
> now, we can install one demo in folder auto-install

Currently the code has not support of several auto-install. But to make it so should't be too hard. I can't tell you precisely in a step-by-step way how to do this. But in general terms you should 1) make some SELECT with available auto-install; 2) somewhere in the code should be $auto_install_dir variable. It should point to the directory with auto-install files. Everything else should remain unchanged.

N.B. This case didn't tested. Worse, I never thought of it. Test your implementation carefully in different environments.

**Comment by xperter** [comment]
@vbarbarosh  Glad to see you are here.
I have just tried what you have said. but not working :(
Can you please make a rough backup with select option.  its really help us lot. 
Already some people asking same thing.  And now a days Most of the theme plan to create with multipurpose. So it will be good for everyone i thing. 

 You can use with $cgi. if any one need multi demo they can just enable this feature

Thanks for your help :)

**Comment by vbarbarosh** [comment]
@xperter I'll try to make some implementation in a week or two.

**Comment by xperter** [comment]
wow great ::+1: 

Thank you so much

**Comment by Ataurr** [comment]
@vbarbarosh  i m also looking  this 👀  Any update ?

**Comment by valeriuzdrobau** [comment]
@vbarbarosh now pursue other modules. Regarding this issue, we will soon introduce a functional, which will allow selecting a demo and then downloading content from the server, I'll let you know here when it will be available this option.

**Comment by Ataurr** [comment]
@valeriuzdrobau  Great news :) please  keep in mind include  this option multi demo select feature from  the server. 
if any one have multi demo. they can use select option to download what they looking for.

**Comment by xperter** [comment]
@vbarbarosh sir any update ?? :)

**Comment by vbarbarosh** [comment]
Hi there. @valeriuzdrobau already said that I no longer work on this project. Nevertheless, the following is a quick implementation of multiple content install.

The whole idea about this method is to force `\FW_Extension_Backup::get_auto_install_dir` return directory different from default one. The most simple method is tho use `$_GET` variable, say `auto-install-dir`. That is just add `&auto-install-dir=some-directory-name` to an URL returned by `$backup->action()->url_backup_auto_install()`. Everything else should remain the same.

### A step by step guide:
1. Make first demo install. Extract it into `demo-install-1`.
2. Make second demo install. Extract it into `demo-install-2`.
3. Copy `demo-install-2/auto-install` to `demo-install-1/auto-install-2`.
4. Update _wp-content/plugins/Unyson-2.3.1/framework/extensions/backup/views/auto-install-1-welcome.php_:
   
   ``` php
   <p>
   <a href="<?php echo esc_attr($backup->action()->url_backup_auto_install()) ?>" onclick="return window.confirm('<?php _e('All your current content will be deleted and replaced with the demo content of the theme!', 'fw'); ?>');" class="button button-primary">
       <?php _e('Import Demo Content 1', 'fw') ?>
   </a>
   |
   <a href="<?php echo esc_attr($backup->action()->url_backup_auto_install()) ?>&amp;auto-install-dir=auto-install-2" onclick="return window.confirm('<?php _e('All your current content will be deleted and replaced with the demo content of the theme!', 'fw'); ?>');" class="button button-primary">
       <?php _e('Import Demo Content 2', 'fw') ?>
   </a>
   </p>
   ```
5. Update `\FW_Extension_Backup::get_auto_install_dir`:
   
   ``` php
   
   public function get_auto_install_dir()
   {
   $auto_install_dir = FW_Request::GET('auto-install-dir', 'auto-install');
   $auto_install_dir = get_template_directory() . '/' . $auto_install_dir;
   
   if (is_dir($auto_install_dir)) {
       return $auto_install_dir;
   }
   
   return false;
   }
   ```

That's it. Now you should be able to choose which demo content to install.

Enjoy!

**Comment by xperter** [comment]
@vbarbarosh  i have read above valeriuzdrobau comment. valeriuzdrobau said you are working with new extension. i am asking about this. :)
as this no longer update that's why we dont want to use this.  we are waiting for your new build demo installation extension. so i am asking any update for new extension when it will be ready for us :P 

Thank you

**Comment by vbarbarosh** [comment]
@xperter Currently I'm not working on Unyson at all. And @valeriuzdrobau is a maintainer of `Backup Extension`.

**Comment by linkinf88k** [comment]
@vbarbarosh I edited the extension in the plugin, everything ok.
 How can overwrite it in scratch theme ?

**Comment by valeriuzdrobau** [comment]
@linkinf88k
1. Move extension from plugin into your `framework-customizations` folder from your theme;
2. remove the following code from `manifest.php`:
`$manifest['github_update'] = 'ThemeFuse/Unyson-Backup-Extension';`

**Comment by dylan-ngo11** [comment]
I'll try to use the above ways while waiting a new function

**Comment by pear1** [comment]
Hello, 

I am trying to move backup extension to the theme, but I got this error message:

**Fatal error:** Cannot redeclare class FW_Backup_Exception in **X\Web\www\wp\wp-content\themes\theme\framework-customizations\extensions\backup\includes\exceptions\exception-fw-backup.php on line 10**

**Comment by ghost** [comment]
Hi,

You can't move extensions to theme

**Comment by pear1** [comment]
@moldcraft  Then how can I make a multiple demo install support?

I just followed these steps:
_1. Move extension from plugin into your framework-customizations folder from your theme;
2. remove the following code from manifest.php:
$manifest['github_update'] = 'ThemeFuse/Unyson-Backup-Extension';_

Can't you just update \FW_Extension_Backup::get_auto_install_dir to something like this?

```
    public function get_auto_install_dir()
    {
        $get_auto_install_dir = FW_Request::GET('auto-install-dir', 'auto-install');
        if( isset($get_auto_install_dir) && $get_auto_install_dir ) {
            $auto_install_dir = get_template_directory() . '/' . $get_auto_install_dir ;
        } else {
            $auto_install_dir = get_template_directory() . '/auto-install';
        }

        if (is_dir($auto_install_dir)) {
            return $auto_install_dir;
        }

        return false;
    }
```

This feature is very important, because at this moment all powerful themes have at least 2 demo installations.

**Comment by pear1** [comment]
Only issues then would be demo content location, because if in the main folder there would be folders: auto-install, auto-install-2, auto-install-3, auto-install-4, auto-install-5, auto-install-6 ... then it wouldn't look so good.

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
