### ISSUE TITLE
Import url improvements

### ISSUE THREAD

**Issue by valeriuzdrobau** [ThemeFuse/Unyson-Backup-Extension#5]
[It](https://github.com/ThemeFuse/Unyson-Backup-Extension/commit/5c848b1d229489ac6f586a515fe846fdefc3cb66) should be improved if possible. You need to add the ability to replace the links with an arbitrary number of backslashes.

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
