### ISSUE TITLE
No sidebar when using Content Install

### ISSUE THREAD

**Issue by maiakhoa** [ThemeFuse/Unyson-Backup-Extension#6]
After I backup the data with Demo package, I install it on another site, all data was fine excerpt Sidebar data, anyone have the same issue, please help me to solve it ?

**Comment by llemurya** [comment]
@maiakhoa this is a bug from sidebars, we will fixed it. Thanks for bug reporting.

**Comment by maiakhoa** [comment]
thanks

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
