### ISSUE TITLE
sitemap.xml. File is not writable

### ISSUE THREAD

**Issue by MrNoSox** [ThemeFuse/Unyson-Backup-Extension#7]
After activating the backup extension, I get this error on the Unyson extensions screen. I have this installed on a multi-site and using the scratch-child theme.

![screen shot 2015-04-27 at 1 30 42 pm](https://cloud.githubusercontent.com/assets/3986335/7353489/e7fe024e-ece1-11e4-97f4-b8f38e3b529a.png)

**Comment by ghost** [comment]
> After activating the backup extension

The warning comes from the SEO extension.

---

Try to create `sitemap.xml` manually and give it write permissions.
