### ISSUE TITLE
One or more database tables are unavailable. The database may need to be repaired.

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson-Backup-Extension#9]
When tried to install  demo data its stacked in white screen. when i refresh the page this  message displayed <pre>One or more database tables are unavailable. The database may need to be repaired.</pre>

and when i tried to repaired database. and this was displayed

<pre>
wp_usermeta: Table 'C76134_wordpress0.wp_usermeta' doesn't exist
wp_posts: Table 'C76134_wordpress0.wp_posts' doesn't exist
wp_comments: Table 'C76134_wordpress0.wp_comments' doesn't exist
wp_links: Table 'C76134_wordpress0.wp_links' doesn't exist
wp_options: Table 'C76134_wordpress0.wp_options' doesn't exist
wp_postmeta: Table 'C76134_wordpress0.wp_postmeta' doesn't exist
wp_terms: Table 'C76134_wordpress0.wp_terms' doesn't exist
wp_term_taxonomy: Table 'C76134_wordpress0.wp_term_taxonomy' doesn't exist
wp_term_relationships: Table 'C76134_wordpress0.wp_term_relationships' doesn't exist
wp_commentmeta: Table 'C76134_wordpress0.wp_commentmeta' doesn't exist
</pre>

What will be the cause this error ??

**Comment by valeriuzdrobau** [comment]
Hi ! please tell me which version of MySQL you use.

**Comment by Ataurr** [comment]
Version 5.0.68

**Comment by valeriuzdrobau** [comment]
It is very likely that you have the same problem as [here](https://github.com/ThemeFuse/Unyson/issues/680). To check, try to search in `database.txt` following excerpt: `utf8mb4`.

**Comment by valeriuzdrobau** [comment]
Anything new? Have you checked what I wrote above?

**Comment by Ataurr** [comment]
Yesterday also getting same issue. i have modified utf8mb4 to utf8 also

but i forget to inform you 
also a message showing on top when i reinstall the wordpress and tried to install all extension again  <pre> Could not create post of type fw_backup</pre>

**Comment by valeriuzdrobau** [comment]
Send me please access details (FTP and phpmyadmin) to the email address valeriuzdrobau@gmail.com.

**Comment by ghost** [comment]
Hello,

In [Unyson v2.4.10](https://wordpress.org/plugins/unyson/changelog/), we released a [new version of the Backup extension](https://github.com/ThemeFuse/Unyson-Backups-Extension), which fixes all problems in Backup v1.

We will not fix the problems in Backup v1, instead we recommend you to upgrade your theme to use the **Backup & Demo Content** extension.
The new extension works completely different, that means you will need to re-create your demo install(s). Please [read the docs](http://manual.unyson.io/en/latest/extension/backups/#content)

Make sure to remove `'backup'` from `$manifest['supported_extensions']` in `{theme}/framework-customizations/theme/manifest.php`
